version: "3.6"

services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:management'
    networks:
      - jandchase_network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  config-ms:
    container_name: config-ms
    image: costanzopa/config-ms
    networks:
      - jandchase_network
    ports:
      - "8088:8088"
    depends_on:
      - rabbitmq

  eureka-ms:
    container_name: eureka-ms
    image: costanzopa/eureka-ms
    networks:
      - jandchase_network
    ports:
      - "8761:8761"
    depends_on:
      - config-ms

  gateway-ms:
    container_name: gateway-ms
    image: costanzopa/gateway-ms
    networks:
      - jandchase_network
    ports:
      - "8091:8091"
    depends_on:
      - eureka-ms

  products-ms:
    image: costanzopa/products-ms
    container_name: products-ms
    networks:
      - jandchase_network
    depends_on:
      - jandchase-api-db
      - gateway-ms

  users-ms:
    image: costanzopa/users-ms
    container_name: users-ms
    networks:
      - jandchase_network
    depends_on:
      - products-ms

  jandchase-api-db:
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    container_name: jandchase-api-db
    networks:
      - jandchase_network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jandchase-api-db
    volumes:
      - db-data-2:/var/lib/mysql

networks:
  jandchase_network:

# Volumes
volumes:
  db-data-2: