version: "3.6"

services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:management'
    networks:
      - jandchase_network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  config-ms:
    container_name: config-ms
    image: costanzopa/config-ms
    networks:
      - jandchase_network
    ports:
      - "8088:8088"
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.99.100:8088"]
      interval: 30s
      timeout: 10s
      retries: 5

  eureka-ms:
    container_name: eureka-ms
    image: costanzopa/eureka-ms
    networks:
      - jandchase_network
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.99.100:8761"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway-ms:
    container_name: gateway-ms
    image: costanzopa/gateway-ms
    networks:
      - jandchase_network
    ports:
      - "8091:8091"
    depends_on:
      - config-ms
      - eureka-ms

    products-ms:
      image: costanzopa/products-ms
      networks:
        - jandchase_network
      depends_on:
        - config-ms
        - eureka-ms
        - products-ms-db
        - gateway-ms

    products-ms-db:
      restart: always
      image: mysql
      networks:
        - jandchase_network
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: products-ms-db
      volumes:
        - ./data:/var/lib/mysql

networks:
  jandchase_network: