version: "3.6"

services:

  products-ms:
    image: costanzopa/products-ms
    container_name: products-ms
    depends_on:
      - products-ms-db

  products-ms-db:
    restart: always
    image: mysql
    container_name: products-ms-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products-ms-db
    volumes:
      - './.data/conf:/etc/mysql/conf.d'

networks:
  default:
    external:
      name: configms_jandchase_network
